DROP VIEW "CMO_DB"."V_CHECK_ROLES_RELATIONSHIP_V10";
CREATE VIEW "CMO_DB"."V_CHECK_ROLES_RELATIONSHIP_V10" ( "ORG_RELATIONSHIPID",
	 "ROLE_MAPPINGID",
	 "ROLE_MAPPING_ACTIVE",
	 "ROLE_ID",
	 "ROLE",
	 "ROLE_DESCRIPTION",
	 "GROUP_DESCRIPTION" ) AS SELECT
	 RM.ORG_RELATIONSHIPSID AS ORG_RELATIONSHIPID,
	 RM.ROLE_MAPPINGID,
	 RM.ACTIVE AS ROLE_MAPPING_ACTIVE,
	 RM.ROLE_ID,
	 ROLE.ROLE,
	 ROLE.ROLE_DESCRIPTION,
	 G.DESCRIPTION AS GROUP_DESCRIPTION 
FROM "ROLE_MAPPING" RM 
INNER JOIN "ROLES" ROLE ON ROLE."ROLE_ID" = RM."ROLE_ID" 
INNER JOIN "ROLES_TYPES" G ON ROLE."ROLES_TYPES_ID" = G."ROLES_TYPES_ID" WITH READ ONLY
